# Site settings
title: 'Alonso López Romo'
description: 'Business Card Page'
url: 'https://alonsolopezr.github.io/'
baseurl: ''
profilepic: '/images/alr-normal.jpg'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
# font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Alonso López Romo'
  email: alonsolopez@uthermosillo.edu.mx
  twitter_username: aloncello
#  facebook_username: joshgerdes
  github_username:  alonsolopezr
  gitlab_username:  alonsolopez
  linkedin_username:  jose-alonso-lopez-romo-b426342/
#  meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
